CONFIG_NAME: "FinalParamsSmall"
MODEL:
  DROPOUT: 0.25
  RECURRENT_DROPOUT: 0.0
  USE_RNN: True
  RNN: "lstm"
  RNN_SIZE: 50
  USE_CNN: True
  CNN_LAYERS: 1
  NUM_FILTERS: 40
  FILTER_SIZE: 3
  MAX_POOL_SIZE: 2
  CLASSIFIER: "crf"
  EMBEDDING_SIZE: 100
TRAINING:
  DATASET: "french"
  MINI_BATCH_SIZE: 64
  EPOCHS: 2
