CONFIG_NAME: "FinalParamsLarge"
MODEL:
  DROPOUT: 0.25
  RECURRENT_DROPOUT: 0.0
  USE_RNN: True
  RNN: "lstm"
  RNN_SIZE: 300
  USE_CNN: True
  CNN_LAYERS: 2
  NUM_FILTERS: 200
  FILTER_SIZE: 3
  MAX_POOL_SIZE: 2
  CLASSIFIER: "crf"
  EMBEDDING_SIZE: 300
TRAINING:
  DATASET: "french"
  MINI_BATCH_SIZE: 64
  EPOCHS: 1
